
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 23 2026 12:50:32 IST (Feb 23 2026 07:20:32 UTC)

// Verification Directory fv/four_bit_adder 

module four_bit_adder(A, B, C0, S, C4);
  input [3:0] A, B;
  input C0;
  output [3:0] S, C4;
  wire [3:0] A, B;
  wire C0;
  wire [3:0] S, C4;
  wire n_0, n_2, n_4;
  assign C4[1] = 1'b0;
  assign C4[2] = 1'b0;
  assign C4[3] = 1'b0;
  ADDFX2 g242__2398(.A (B[3]), .B (A[3]), .CI (n_4), .CO (C4[0]), .S
       (S[3]));
  ADDFX2 g243__5107(.A (B[2]), .B (A[2]), .CI (n_2), .CO (n_4), .S
       (S[2]));
  ADDFX2 g244__6260(.A (B[1]), .B (A[1]), .CI (n_0), .CO (n_2), .S
       (S[1]));
  ADDFX2 g245__4319(.A (A[0]), .B (C0), .CI (B[0]), .CO (n_0), .S
       (S[0]));
endmodule

