
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 16 2026 13:27:23 IST (Feb 16 2026 07:57:23 UTC)

// Verification Directory fv/counter 

module counter(clk, rst, m, count);
  input clk, rst, m;
  output [3:0] count;
  wire clk, rst, m;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  INVXL g159(.A (n_7), .Y (n_8));
  NOR2XL g160__2398(.A (n_1), .B (n_6), .Y (n_7));
  CLKINVX1 g161(.A (n_5), .Y (n_6));
  AOI221X1 g162__5107(.A0 (n_2), .A1 (m), .B0 (count[1]), .B1 (n_4),
       .C0 (n_3), .Y (n_5));
  MXI2XL g164__6260(.A (n_2), .B (count[1]), .S0 (count[0]), .Y (n_3));
  MXI2XL g163__4319(.A (n_2), .B (count[1]), .S0 (count[2]), .Y (n_1));
  CLKINVX1 g169(.A (count[1]), .Y (n_2));
  INVXL g168(.A (rst), .Y (n_9));
  CLKINVX1 g166(.A (m), .Y (n_4));
  DFFRX2 \count_reg[0] (.RN (n_9), .CK (clk), .D (n_0), .Q (count[0]),
       .QN (n_0));
  SDFFRHQX2 \count_reg[3] (.RN (n_9), .CK (clk), .D (n_7), .SI (n_8),
       .SE (count[3]), .Q (count[3]));
  SDFFRHQX2 \count_reg[2] (.RN (n_9), .CK (clk), .D (n_5), .SI (n_6),
       .SE (count[2]), .Q (count[2]));
  SDFFRHQX2 \count_reg[1] (.RN (n_9), .CK (clk), .D (n_4), .SI (m), .SE
       (n_3), .Q (count[1]));
endmodule

