
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  2 2026 13:25:34 IST (Mar  2 2026 07:55:34 UTC)

// Verification Directory fv/booth_new 

module booth_new(a, b, c, rst, clk);
  input [3:0] a, b;
  input rst, clk;
  output [7:0] c;
  wire [3:0] a, b;
  wire rst, clk;
  wire [7:0] c;
  wire [8:0] P;
  wire [8:0] S;
  wire [8:0] A;
  wire [31:0] i;
  wire n_0, n_4, n_5, n_6, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_75, n_76, n_77;
  assign c[6] = c[7];
  DFFQX1 \P_reg[7] (.CK (clk), .D (n_64), .Q (P[7]));
  OAI211XL g2179__2398(.A0 (n_54), .A1 (n_18), .B0 (n_37), .C0 (n_63),
       .Y (n_64));
  NAND2XL g2181__5107(.A (n_62), .B (n_60), .Y (n_63));
  DFFQX1 \P_reg[6] (.CK (clk), .D (n_61), .Q (P[6]));
  OAI21XL g2183__6260(.A0 (n_57), .A1 (n_58), .B0 (n_59), .Y (n_62));
  OAI2BB1XL g2182__4319(.A0N (n_56), .A1N (n_60), .B0 (n_53), .Y
       (n_61));
  NAND2XL g2186__8428(.A (n_58), .B (n_57), .Y (n_59));
  DFFQX1 \P_reg[4] (.CK (clk), .D (n_55), .Q (P[4]));
  ADDFXL g2188__5526(.A (S[7]), .B (P[7]), .CI (n_40), .CO (n_57), .S
       (n_56));
  CLKINVX1 g2190(.A (n_52), .Y (n_55));
  AOI21XL g2192__6783(.A0 (n_49), .A1 (n_48), .B0 (n_50), .Y (n_54));
  AOI222XL g2187__3680(.A0 (n_77), .A1 (P[6]), .B0 (P[7]), .B1 (n_76),
       .C0 (n_46), .C1 (n_43), .Y (n_53));
  DFFQX1 \P_reg[5] (.CK (clk), .D (n_47), .Q (P[5]));
  AOI222XL g2191__1617(.A0 (n_42), .A1 (n_21), .B0 (rst), .B1 (b[3]),
       .C0 (n_77), .C1 (P[4]), .Y (n_52));
  NOR2XL g2194__2802(.A (n_49), .B (n_48), .Y (n_50));
  OAI2BB1XL g2195__1705(.A0N (n_41), .A1N (n_60), .B0 (n_45), .Y
       (n_47));
  SDFFQX1 \S_reg[8] (.CK (clk), .D (S[8]), .SI (n_36), .SE (rst), .Q
       (S[8]));
  ADDFXL g2196__5122(.A (A[7]), .B (P[7]), .CI (n_16), .CO (n_48), .S
       (n_46));
  SDFFQX1 \S_reg[7] (.CK (clk), .D (S[7]), .SI (n_32), .SE (rst), .Q
       (S[7]));
  AOI222XL g2198__8246(.A0 (n_77), .A1 (P[5]), .B0 (P[6]), .B1 (n_76),
       .C0 (n_27), .C1 (n_43), .Y (n_45));
  DFFQX1 \i_reg[1] (.CK (clk), .D (n_38), .Q (i[1]));
  OAI22X1 g2201__7098(.A0 (n_39), .A1 (n_35), .B0 (n_0), .B1 (n_34), .Y
       (n_42));
  ADDFX1 g2206__6131(.A (S[6]), .B (P[6]), .CI (n_39), .CO (n_40), .S
       (n_41));
  NOR2XL g2204__1881(.A (n_33), .B (rst), .Y (n_38));
  OAI21X1 g2205__5115(.A0 (n_77), .A1 (n_76), .B0 (P[7]), .Y (n_37));
  DFFQX1 \P_reg[3] (.CK (clk), .D (n_28), .Q (P[3]));
  OAI21XL g2197__7482(.A0 (a[3]), .A1 (n_31), .B0 (n_29), .Y (n_36));
  DFFQX1 \P_reg[2] (.CK (clk), .D (n_26), .Q (P[2]));
  DFFQX1 \P_reg[1] (.CK (clk), .D (n_25), .Q (P[1]));
  DFFQX1 \i_reg[2] (.CK (clk), .D (n_30), .Q (i[2]));
  SDFFQX1 \S_reg[6] (.CK (clk), .D (S[6]), .SI (n_11), .SE (rst), .Q
       (S[6]));
  DFFQX1 \i_reg[0] (.CK (clk), .D (n_23), .Q (i[0]));
  DFFQX1 \P_reg[0] (.CK (clk), .D (n_24), .Q (P[0]));
  AOI21X1 g2212__4733(.A0 (A[5]), .A1 (n_34), .B0 (P[5]), .Y (n_35));
  MXI2XL g2213__6161(.A (n_13), .B (i[1]), .S0 (i[2]), .Y (n_33));
  AOI21XL g2210__9315(.A0 (a[2]), .A1 (n_14), .B0 (n_31), .Y (n_32));
  AOI2BB1X1 g2211__9945(.A0N (i[2]), .A1N (n_12), .B0 (rst), .Y (n_30));
  NAND2XL g2200__2883(.A (a[3]), .B (n_31), .Y (n_29));
  SDFFQX2 \c_reg[2] (.CK (clk), .D (c[2]), .SI (P[3]), .SE (n_77), .Q
       (c[2]));
  SDFFQX2 \c_reg[0] (.CK (clk), .D (c[0]), .SI (P[1]), .SE (n_77), .Q
       (c[0]));
  SDFFQX2 \c_reg[3] (.CK (clk), .D (c[3]), .SI (P[4]), .SE (n_77), .Q
       (c[3]));
  CLKINVX1 g2223(.A (n_19), .Y (n_28));
  MXI2XL g2227__2346(.A (n_39), .B (n_15), .S0 (n_10), .Y (n_27));
  CLKINVX1 g2224(.A (n_22), .Y (n_26));
  CLKINVX1 g2222(.A (n_20), .Y (n_25));
  SDFFQX2 \c_reg[5] (.CK (clk), .D (c[5]), .SI (P[6]), .SE (n_77), .Q
       (c[5]));
  EDFFHQX4 \c_reg[6] (.CK (clk), .D (P[7]), .E (n_77), .Q (c[7]));
  SDFFQX2 \c_reg[1] (.CK (clk), .D (c[1]), .SI (P[2]), .SE (n_77), .Q
       (c[1]));
  SDFFQX2 \c_reg[4] (.CK (clk), .D (c[4]), .SI (P[5]), .SE (n_77), .Q
       (c[4]));
  OAI2BB1XL g2239__1666(.A0N (P[0]), .A1N (n_77), .B0 (n_17), .Y
       (n_24));
  NOR2XL g2240__7410(.A (n_75), .B (rst), .Y (n_23));
  AOI222XL g2229__6417(.A0 (P[3]), .A1 (n_21), .B0 (rst), .B1 (b[1]),
       .C0 (n_77), .C1 (P[2]), .Y (n_22));
  AOI222XL g2226__2398(.A0 (P[2]), .A1 (n_21), .B0 (rst), .B1 (b[0]),
       .C0 (n_77), .C1 (P[1]), .Y (n_20));
  AOI222XL g2228__5107(.A0 (P[4]), .A1 (n_21), .B0 (rst), .B1 (b[2]),
       .C0 (n_77), .C1 (P[3]), .Y (n_19));
  CLKINVX1 g2225(.A (n_18), .Y (n_43));
  NOR2XL g2242__6260(.A (P[0]), .B (n_17), .Y (n_60));
  NAND3X1 g2231__4319(.A (P[0]), .B (n_5), .C (n_21), .Y (n_18));
  AOI21X1 g2241__8428(.A0 (n_15), .A1 (n_8), .B0 (n_9), .Y (n_16));
  NOR2XL g2233__5526(.A (a[2]), .B (n_14), .Y (n_31));
  ADDHXL g2234__6783(.A (i[1]), .B (i[0]), .CO (n_12), .S (n_13));
  AOI21XL g2243__3680(.A0 (a[1]), .A1 (a[0]), .B0 (n_4), .Y (n_11));
  NAND2BX1 g2245__1617(.AN (n_9), .B (n_8), .Y (n_10));
  SDFFQX1 \A_reg[7] (.CK (clk), .D (A[7]), .SI (a[2]), .SE (rst), .Q
       (A[7]));
  NAND2XL g2244__2802(.A (P[1]), .B (n_21), .Y (n_17));
  SDFFQX1 \A_reg[8] (.CK (clk), .D (A[8]), .SI (a[3]), .SE (rst), .Q
       (A[8]));
  MXI2XL g2248__5122(.A (P[7]), .B (n_6), .S0 (A[8]), .Y (n_49));
  MXI2XL g2247__8246(.A (P[7]), .B (n_6), .S0 (S[8]), .Y (n_58));
  SDFFQX1 \A_reg[6] (.CK (clk), .D (A[6]), .SI (a[1]), .SE (rst), .Q
       (A[6]));
  SDFFQX1 \A_reg[5] (.CK (clk), .D (A[5]), .SI (a[0]), .SE (rst), .Q
       (A[5]));
  MXI2XL g2249__7098(.A (n_5), .B (P[1]), .S0 (P[0]), .Y (n_34));
  INVXL g2250(.A (n_4), .Y (n_14));
  CLKINVX1 g2251(.A (n_15), .Y (n_39));
  NOR2XL g2252__1881(.A (A[6]), .B (P[6]), .Y (n_9));
  NOR2XL g2253__5115(.A (a[1]), .B (a[0]), .Y (n_4));
  NAND2XL g2256__7482(.A (A[6]), .B (P[6]), .Y (n_8));
  NAND2XL g2254__4733(.A (A[5]), .B (P[5]), .Y (n_15));
  NOR2XL g2257__6161(.A (i[2]), .B (rst), .Y (n_21));
  CLKINVX1 g2259(.A (P[1]), .Y (n_5));
  CLKINVX1 g2261(.A (P[7]), .Y (n_6));
  INVXL g2262(.A (P[5]), .Y (n_0));
  XOR2XL g2(.A (i[2]), .B (i[0]), .Y (n_75));
  NOR2BX1 g2289(.AN (n_21), .B (n_34), .Y (n_76));
  NOR2BX1 g2290(.AN (i[2]), .B (rst), .Y (n_77));
endmodule

